language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs_config.php -v --dry-run --stop-on-violation --using-cache=no
  - vendor/bin/phpunit --coverage-clover=build/coverage.clove

after_script:
  - if [ $(phpenv version-name) == "7.0" ]; wget https://scrutinizer-ci.com/ocular.phar -O build/ocular.phar ; fi
  - if [ $(phpenv version-name) == "7.0" ]; php build/ocular.phar code-coverage:upload --format=php-clover build/coverage.clover ; fi
